### ISSUE TITLE
[22년 11월 5주차] 작업 일지

### ISSUE THREAD

**Issue by tonykang22** [tonykang22/hello-world-auto-store#127]
# Common
- [x] Controller response :: 날짜 String 값으로 변경
    * [x] product-analyzer
    * [x] product-manager
- [x] `spring.datasource.hikari.connection-timeout` 60초로 설정
- [x] 모듈 분리에 따른 작업 (#373 )

----

- [ ] 중국 상품 소싱 API 리서치 (#376 )
    * [x] 오마이집 관련해서도 리서치
- [x] ddl 설정 변경

<br>

----

<br>

# Product Analyzer
- [x] 새로 배포 시 참조할 pointer 값 설정
    * [x] Controller에서도 관리할 수 있도록
- [x] script 업데이트 (`pointer-context` 폴더 생성)

----

- [x] 판매 상품 평균 가격 선정 (#382 )
    * 최저 가격 제한 : $50 → $40
- [x] SourcingResults 성공 메세지에 키워드 추가
- [x] 등록될 상품 제목에서 검색어 삭제
- [x] 금기어 파일로 두기
    * 파일 대신 db 두기로 결정 (#383 )
---

- [x] 소싱 상품[아마존] 옵션 관련 이슈 (#405 )

---

- [x] 소싱 상품의 최소 재고 5개로 변경
- [x] pointer: 파일 생성 시에만 초기화 (#408 )
- [ ] 가중치를 적용할 수 있는 방안 고려
- [ ] 특정 ASIN 소싱 기능 (#420 )

##### 우선순위 낮음
 * [ ] 엑셀파일 업로드 기능(신규 파일 업로드)
 * [ ] 로그 아카이빙
 * [ ] 이미지 번역 적용
    - Papago Image Translation 사용
 * [ ] 분석에 사용되는 활용 지표 추가 고려
    - 블랙키위, 일헥타르 …

<br>

# Product Analyzer v2
 * todo

<br>

---

<br>

# Product Manager
- [x] 쿠팡 등록 상품 갯수 낮추기 (9999 -> 5) (#358 )
- [x] `create Product` cron schedule 변경 (#363) 
- [x] `delete Product` 개선
    * [x] `상품명` 검색해서 삭제
    * [x] 판매가가 특정 이상인 경우 검색해서 삭제
- [x] 작업 수행 성공 시에도 slack 메세지 전송

----

- [x] 쿠팡 등록 상품 갯수 낮추기 (9999 -> 5) (#358 )
    * [x] 기존의 등록된 상품도 마찬가지로 갯수 개선할 API 존재 여부 파악 및 적용
- [x] 아이템위너가 아닌 상품 삭제 방안 찾기 (#381 )
- [x] 상품 삭제 시, 삭제한 내역 정보도 슬랙 알람으로 전송

----

- [x] sync() 메서드 파악 및 개선사항 파악
    * [x] sync() 주기 설정: 2주
- [ ] 소싱된 특정 ASIN 상품 등록 기능 (#421 )

---
### 추후 확인
* [ ] Coupang Wing <-> MySQL HWAS DB 간 Sync 기능
    - 전체 상품에 대해 판매 상태 Sync 필요(ON, OFF, TBD)
* [ ] 상품 생성/조회/수정/삭제 API
   - 수정
      * [ ] 판매중인 전체 상품 판매 상태 변경(ON, OFF, TBD)
      * [ ] 판매중인 특정 상품 판매 중지(아예 중지, 일시 중지)
       - Status 입력받아 전체 상품 판매(ON), 일시 중지(TBD) 또는 판매 종료(OFF) 

<br>

---

<br>

# Order Manager
- [ ] 해당 이슈 관련, 주문 확인할 방법 고안 (#342 )
    * [ ] 적용
- [x] Zinc TrackingUpdate Webhook 두 번 들어오는 이슈
- [x] 예외 상황 추가 (#411 )

### 우선 순위 낮음 (추후 적용)
- [ ] 추후 확장성 고려한 설계 추가
    * [ ] order-manager 인터페이스화 (#152 )

<br>

---

<br>

# CS Manager
 - [ ] 확장성을 고려한 설계
 - [ ] 구현 (#297 )
    * [x] 고객의 주문이 확인되면 웰컴 메세지를 전송한다.
    * [x] 배송 정보를 확인할 수 있는 배송 현황 조회 기능을 제공한다.
    * [ ] 취소/환불 관련 메세지를 제공한다.
    * [ ] (쿠팡의 경우) 1:1 문의 접수 여부를 체크한다.
- [ ] 고객 문의 db 추가 (#407 )
