### ISSUE TITLE
[22년 12월 2주차] 작업 일지

### ISSUE THREAD

**Issue by tonykang22** [tonykang22/hello-world-auto-store#134]
# Common
- [ ] 중국 상품 소싱 API 리서치 (#376 )

<br>

----

<br>

# Product Analyzer
- [ ] 가중치를 적용할 수 있는 방안 고려
- [x] 특정 ASIN 소싱 기능 (#420 )
- [x] 오마이집 배송 비용 계산 엑셀 파일 업데이트

##### 우선순위 낮음
 * [ ] 엑셀파일 업로드 기능(신규 파일 업로드)
 * [ ] 로그 아카이빙
 * [ ] 이미지 번역 적용
    - Papago Image Translation 사용
 * [ ] 분석에 사용되는 활용 지표 추가 고려
    - 블랙키위, 일헥타르 …

<br>

---

# Product Analyzer V2
- [x] 키워드 소싱할 사이트 활용 방안 파악 (#453 )
- [x] Java17 호환성 확인 (#440 )
- [ ] 중국 상품 소싱 API 리서치 및 적용 (#376 )

---
<br>

# Product Manager
- [x] Sync: Coupang deleteProduct API 개선
- [x] `deleteStaleProduct`: 파악 및 조건 결정 (#434 )
- [x] 소싱된 특정 ASIN 상품 등록 기능 (#421 )
- [x] 오마이집 배송 비용 계산 엑셀 파일 업데이트

<br>

---

<br>

# Order Manager
- [ ] 해당 이슈 관련, 주문 확인할 방법 고안 (#342 )
    * [ ] 적용
- [x] Kafka Producer 쪽 설정
- [x] 상품 판매 완료 시, DB `product`의 `sold_count` 증가 적용
  * #438 
- [x] 상품 재고 부족 등의 문제 발생 시 개발자에게만 알림 (즉시 취소는 판매자 점수 하락의 주 원인)

### 우선 순위 낮음 (추후 적용)
- [ ] 추후 확장성 고려한 설계 추가
    * [ ] order-manager 인터페이스화 (#152 )

<br>

---

<br>

# CS Manager
 - [x] 확장성을 고려한 설계
 - [x] 구현 (#297 )
    * [x] 취소/환불 관련 메세지를 제공한다. 
        + 추후 메시지 전송 플랫폼이 추가되면 `message.properties`를 통해 전달하기로 한다.
        + 고정 메시지(상수)를 매번 전달하는 방식
    * [x] (쿠팡의 경우) 1:1 문의 접수 여부를 체크한다.
- [x] 고객 문의 db 추가 (#407 )
