### ISSUE TITLE
[23년 2월 1주차] 작업 일지

### ISSUE THREAD

**Issue by tonykang22** [tonykang22/hello-world-auto-store#208]
# Common

----

<br>

----

<br>

# Product Analyzer
- [ ] SelectScore 생성 시 검색 키워드 추가

##### 우선순위 낮음
  * [ ] 검색 키워드에 따른 수수료 부과
 * [ ] 가중치를 적용할 수 있는 방안 고려
 * [ ] 엑셀파일 업로드 기능(신규 파일 업로드)
 * [ ] 이미지 번역 적용
    - Papago Image Translation 사용
 * [ ] 분석에 사용되는 활용 지표 추가 고려
    - 블랙키위, 일헥타르 …

<br>

---

# Product Analyzer V2
- [ ] 소싱할 카테고리 선정 (DB)
- [x] 브랜드 키워드 필터링 (#507)
- [ ] SelectScore 알고리즘 선정
  * [x] 소싱 API 로 가져오는 지표 정리 (#495 )
- [ ] 중국 상품 소싱 API 리서치 및 적용 (#376 )
  * [x] OTAPI (#506 )

---
<br>

# Product Manager
- [ ] 네이버 스마트스토어 대응(#471)
- [ ] 오마이집 상품명 한글 사용 불가 이슈
- [ ] 검색 키워드에 따른 수수료 부과

<br>

---

<br>

# Order Manager

### 우선 순위 낮음 (추후 적용)
- [ ] 추후 확장성 고려한 설계 추가
    * [ ] order-manager 인터페이스화 (#152 )

<br>

---

<br>

# CS Manager
