### ISSUE TITLE
[23년 3월 3주차] 작업 일지

### ISSUE THREAD

**Issue by tonykang22** [tonykang22/hello-world-auto-store#219]
# Common
- [ ] 손익 계산

----

<br>

# Product Analyzer
- [x] SelectScore 생성 시 검색 키워드 추가
- [x] 슬림 서비스 수수료 추가 (product sourcing)
- [x] Webdriver 관련 이슈

##### 우선순위 낮음
 * [x] 검색 키워드에 따른 수수료 부과
    - 건기식 등을 위한 작업이었기 때문에 잠정 중단
 * [ ] 가중치를 적용할 수 있는 방안 고려
 * [ ] 엑셀파일 업로드 기능(신규 파일 업로드)
 * [ ] 이미지 번역 적용
    - Papago Image Translation 사용
 * [ ] 분석에 사용되는 활용 지표 추가 고려
    - 블랙키위, 일헥타르 …

<br>

---

# Product Analyzer V2
- [ ] 소싱할 카테고리 선정 (DB)
  *  [ ] 카테고리 차수 정보 추가
- [x] 브랜드 키워드 필터링 (#507)
- [ ] SelectScore 알고리즘 선정
  * [x] 소싱 API 로 가져오는 지표 정리 (#495 )
- [ ] 중국 상품 소싱 API 리서치 및 적용 (#376 )
  * [x] OTAPI (#506 )

---
<br>

# Product Manager
- [ ] 네이버 스마트스토어 대응(#471)
- [x] 슬림 서비스 수수료 추가 (product syncing)
- [x] 오마이집 상품명 한글 사용 불가 이슈
- [ ] 상품 판매량 Sync (#539 )

<br>

### 우선 순위 낮음 (추후 적용)
- [x] 검색 키워드에 따른 수수료 부과 (검수가 필요한 품목 등)
  * 상품 가격에 `검수 수수료($1)` / `분리 배송 수수료($3)` 부가하는 방식으로 대응 완료 (#484)

<br>

---

<br>

# Order Manager
- [x] 슬림 서비스 적용

### 우선 순위 낮음 (추후 적용)
- [ ] 추후 확장성 고려한 설계 추가
    * [ ] order-manager 인터페이스화 (#152 )

<br>

---

<br>

# CS Manager
- [x] #513
