### ISSUE TITLE
[22년 4월 4주차] 작업 일지

### ISSUE THREAD

**Issue by tonykang22** [tonykang22/hello-world-auto-store#22]
# Product Analyzer
 * [ ] 리팩토링
    - [x] select-score, sourcing-result 파일 분할
    - [ ] FileReader, FileWriter 통합 및 common 이동
    - [ ] 구조 변경
       - [ ] ProductAnalyzer
       - [ ] SelectScoreController, SelectScoreService
       - [ ] AmazonSourcingController, AmazonSourcingService
    - [x] 에러 수정
       - [x] PandaRank 크롤링 이슈
 * [ ] 소싱상품 가중치 조회/수정/삭제
    - [ ] NaverCategory, PandaRank 로 각각 분할 및 가중치 둘 SourcingContext 생성
 * [ ] 엑셀파일 업로드 기능(신규 파일 업로드)
 * [ ] 아이템스카우트 카테고리 필터링
 * [ ] 로그 아카이빙

##### 우선순위 낮음
 * [ ] 이미지 번역 적용
    - Papago Image Translation 사용
 * [ ] 분석에 사용되는 활용 지표 추가 고려
    - 블랙키위, 일헥타르 …

---

# Product Manager
* [ ] 상품 생성/조회/수정/삭제 API
   - 수정
      * [ ] 등록된 상품 가격 및 재고 현황 갱신 (우선순위 낮음)
      * [ ] 판매중인 상품 판매 중지(상태 변경, 전체)
      * [ ] 판매중인 상품 판매 중지(상태 변경, 특정)
      * [ ] 판매중인 상품 판매 정보 수정(특정)

---

# Order Manager

- [ ] 쿠팡에서 사용할 API 파악 및 정리 (등록된 상품의 주문 현황 파악 목적)
    * [ ] 배송지시 ~ 배송중
- [x] Amazon 으로부터 상품 구매할 API 파악 및 정리
    * [x] Zinc (배대지 요청 시) (#135 )
    * [x] Ohmyzip (#140 )
- [ ] 쿠팡에서 주문된 제품 검증 불합격 경우에 대한 설계 및 정리
    * [ ] 구매자에게 바로 취소를 해줘야하는 경우
    * [ ] 판매자(개발자)에게 Slack 알람으로 판단을 전달해야하는 경우
- [ ] 기능 구현 (참고 : #132 )
    * [x] 주문 확인
    * [ ] 구매 가능 여부 판단
- [ ] Thread, Thread Pool에 대해 파악 후, 프로젝트에서 적용 (#139 )
- [x] ASIN 변경 유무 검증 방안 추가
 
---
