### ISSUE TITLE
[23년 4월 4주차] 작업 일지

### ISSUE THREAD

**Issue by tonykang22** [tonykang22/hello-world-auto-store#233]
# Common
- [X] Costco, Homedepot 조사
  * #561
- [x] 실 배송비용 계산
  * #560 
- [x] 클라우드 리소스 사용량 파악
  * #581 
- [x] 예상 정산 금액 모델
  * [x] 쿠팡 실제 정산 데이터 활용 가능성 확인
  * #576 
- [x] 판매 증진 방안 제시
  * #577 

----

<br>

# Admin
- [x] 연/월 별 손익 계산 API
  * #576 

<br>

# Product Analyzer
- [x] 배치 작업 : 분산화
  * #554 
  * [x] 각 작업의 로그 상세 (Parsing Error 의심 부분)
  * [ ] 무한 루프에 빠지는 경우 알람 기능
    + WebClient 적용
- [x] 현 `Select-score / Sourcing-results 로직` 정리
  * #563 
- [ ] CloudFunction 적용
  * #580 

##### 우선순위 낮음
 * [ ] 가중치를 적용할 수 있는 방안 고려
 * [ ] 엑셀파일 업로드 기능(신규 파일 업로드)
 * [ ] 이미지 번역 적용
    - Papago Image Translation 사용
 * [ ] 분석에 사용되는 활용 지표 추가 고려
    - 블랙키위, 일헥타르 …

<br>

---

# Product Analyzer V2
- [ ] Walmart 도입

---
<br>

# Product Manager
- [ ] 네이버 스마트스토어 대응(#471)
- [ ] 상품 판매량 Sync (#539 )
- [x] #579 

<br>

---

<br>

# Order Manager
- [x] Buyboxwinner 변경 시 대응 방안
  * #562 

### 우선 순위 낮음 (추후 적용)
- [ ] 추후 확장성 고려한 설계 추가
    * [ ] order-manager 인터페이스화 (#152 )

<br>

---

<br>

# CS Manager
