### ISSUE TITLE
[23년 5월 1주차] 작업 일지

### ISSUE THREAD

**Issue by tonykang22** [tonykang22/hello-world-auto-store#238]
# Common
- [ ] 리소스 반납 후 서버 재구동
- [ ] [Cloud Log Analytics](https://www.ncloud.com/product/management/cloudLogAnalytics) 적용
- [ ] [Object Storage](https://www.ncloud.com/product/storage/objectStorage) 적용
- [x] Coupang Wing : 판매 이력 없는 상품 모두 삭제

----

<br>

# Admin

<br>

# Product Analyzer
- [ ] CloudFunctions 적용
  * #580 
- [ ] 상품 번역 내역 축소
  * `제목, 설명, 스펙`만 번역

##### 우선순위 낮음
 * [ ] 가중치를 적용할 수 있는 방안 고려
 * [ ] 엑셀파일 업로드 기능(신규 파일 업로드)
 * [ ] 이미지 번역 적용
    - Papago Image Translation 사용
 * [ ] 분석에 사용되는 활용 지표 추가 고려
    - 블랙키위, 일헥타르 …

<br>

---

# Product Analyzer V2
- [ ] Walmart 도입

---
<br>

# Product Manager
- [ ] 네이버 스마트스토어 대응(#471)
- [ ] 상품 판매량 Sync (#539 )
- [x] #579 

<br>

---

<br>

# Order Manager

### 우선 순위 낮음 (추후 적용)
- [ ] 추후 확장성 고려한 설계 추가
    * [ ] order-manager 인터페이스화 (#152 )
- [ ] MQTT 적용

<br>

---

<br>

# CS Manager
- [ ] MQTT 적용
