### ISSUE TITLE
[22년 7월 4주차] 작업 일지

### ISSUE THREAD

**Issue by tonykang22** [tonykang22/hello-world-auto-store#49]
# Product Analyzer v2
 * todo

# Product Analyzer
 * [ ] Rainforest API 사용시 필터링 조건인 minimum price 가 적용되지 않음
    - 최소 가격 이하의 물건들이 소싱됨
 * [ ] SLF4J 충돌 이슈
    - 쿠팡 SDK 의존성 제거

##### 우선순위 낮음
 * [ ] 엑셀파일 업로드 기능(신규 파일 업로드)
 * [ ] 로그 아카이빙
 * [ ] 이미지 번역 적용
    - Papago Image Translation 사용
 * [ ] 분석에 사용되는 활용 지표 추가 고려
    - 블랙키위, 일헥타르 …

---

# Product Manager
* [ ] 소싱 상품의 가격이 5배 이상 뛰는 원인 분석
    - 원래 상품 URL : https://www.amazon.com/dp/B00JGJGQ9A?th=1
    - 원래 상품 가격 : $66 ~ $95
    - Product Manager 에서 쿠팡에 등록한 상품 가격 : 54만원
    - 예상되는 이유로는 항공 배송비....(?)
* [ ] Coupang Wing <-> MySQL HWAS DB 간 Sync 기능
    - 전체 상품에 대해 판매 상태 Sync 필요(ON, OFF, TBD)
* [ ] 상품 생성/조회/수정/삭제 API
   - 수정
      * [ ] 판매중인 전체 상품 판매 상태 변경(ON, OFF, TBD)
      * [ ] 판매중인 특정 상품 판매 중지(아예 중지, 일시 중지)
       - Status 입력받아 전체 상품 판매(ON), 일시 중지(TBD) 또는 판매 종료(OFF) 

---

# Order Manager

- [x] 기능 구현 (참고 : #132 )
    * [x] 배대지 결제
        * [x] 배대지 신청 시 카테고리 고려 (#246 )
- [x] Zinc API 대체하기
    * [x] Selenium 사용해 대체하기 (#238  )
- [x] order-manager 모듈 완전 분리하기 (common 모듈 사용하지 않는 방향)
- [x] Controller 두기 (실패한 task queue size 등의 정보)
- [x] SLF4J 충돌 이슈
    * [x] SDK 분리
    * [x] 로그백 적용되는지 확인
- [ ] 추후 확장성 고려한 설계 추가
    * [ ] order-manager 인터페이스화 (#152 )
- [ ] 전반적으로 빈약한 테스트 추가 작성
- [ ] order-manager script 작성
- [ ] 기능 구현
    * [ ] 쿠팡 상품 취소 시
        * [ ] 각 단계에 따른 취소 시나리오 예상
        * [ ] 해당 시나리오에 대한 취소 프로세스 구현
    * [ ] 판매완료 및 취소 상품 정보 저장
        * [ ] order-manager에서 사용할 table 설계
        * [ ] controller 구현
    * [ ] 배송 현황 조회 기능

---
